### ISSUE TITLE
Interested

### ISSUE THREAD

**Issue by compumatter** [brillantesmanuel/gift_cards#1]
I'm looking for a Gift Card code base for my clients websites.   I see you just uploaded this and was wondering if it was usable and what your thoughts were?

Thanks

**Comment by brillantesmanuel** [comment]
Hi this won't be a plugin. This is a full site. but intented for registration until to generating a gift code.

**Comment by brillantesmanuel** [comment]
Sorry for the late reply this will be a full site intended for registration and generating a gift code.
